services:
  lab1:
    build: lab1
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    mem_limit: 512m
    ports:
      - "6379:6379"
