services:
  lab1:
    build: lab1
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    mem_limit: 512m
    ports:
      - "6379:6379"
