services:
  sync:
    build: sync-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8080:8080

  async:
    build: async-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1

  ext-api:
    container_name: ext-api-service
    build: ext-api-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60