services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: jdbc_schema
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - my_custom_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d jdbc_schema" ]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: lab2
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my_custom_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jdbc_schema
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret
volumes:
  pg-data:

networks:
  my_custom_network:
    driver: bridge
