services:
  provider-service:
    build: provider-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  consumer-service:
    build: consumer-service
    mem_limit: 512m
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker