server.port: 7002

app:
  provider-service:
    host: localhost
    port: 7001

---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  provider-service:
    host: provider-service
    port: 8081
